# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76426d17be533dcb5db5da10b7cfdad4b780b98c8606102d66cc27dfa0573b81fa8597fc3b980db1980a82c8d0fa4e410da225c09f01c369f0301a857ffa77b3

test:
  secret_key_base: 87756876f3f80cda3fbdef0ca1b63dfdf343b18989d0ea29ecc127e0e3eee4eb01f9347f2a45572e6dcabd73e9ed827b5be15021b9d68bd0b0180a4e8df3ab23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
